name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run API tests
    - name: Run API tests
      run: |
        source .venv/bin/activate
        PYTHONPATH=$(pwd) pytest app/api/test_api.py

    # Step 5: Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        source .venv/bin/activate
        pip install -r app/frontend/requirements.txt

    # Step 6: Run frontend tests
    - name: Run frontend tests
      run: |
        source .venv/bin/activate
        cd app/frontend
        PYTHONPATH=$(pwd) pytest test_front.py -v --tb=short
      
    # Step 7: Zip project for backup if tests pass
    - name: Zip project for backup
      if: ${{ success() }}
      run: |
        zip -r project-backup.zip app

    # Step 8: Upload backup artifact
    - name: Upload backup artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: project-backup
        path: project-backup.zip